In [1]:
import pandas as pd

In [4]:
tb = pd.read_csv('tb.csv')

In [5]:
tb

,iso2,year,new_sp,new_sp_m04,new_sp_m514,new_sp_m014,new_sp_m1524,new_sp_m2534,new_sp_m3544,new_sp_m4554,...,new_sp_f04,new_sp_f514,new_sp_f014,new_sp_f1524,new_sp_f2534,new_sp_f3544,new_sp_f4554,new_sp_f5564,new_sp_f65,new_sp_fu
0,AD,1989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AD,1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AD,1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AD,1992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AD,1993,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,AD,1994,24.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,AD,1996,8.0,NaN,NaN,0.0,0.0,0.0,4.0,1.0,...,NaN,NaN,0.0,1.0,1.0,0.0,0.0,1.0,0.0,NaN
7,AD,1997,17.0,NaN,NaN,0.0,0.0,1.0,2.0,2.0,...,NaN,NaN,0.0,1.0,2.0,3.0,0.0,0.0,1.0,NaN
8,AD,1998,1.0,NaN,NaN,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,AD,1999,4.0,NaN,NaN,0.0,0.0,0.0,1.0,1.0,...,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,NaN
10,AD,2000,1.0,NaN,NaN,0.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,AD,2001,3.0,NaN,NaN,0.0,NaN,NaN,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,AD,2002,2.0,NaN,NaN,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN
13,AD,2003,7.0,NaN,NaN,0.0,0.0,0.0,1.0,2.0,...,NaN,NaN,0.0,1.0,1.0,1.0,0.0,0.0,0.0,NaN
14,AD,2004,3.0,NaN,NaN,0.0,0.0,0.0,1.0,1.0,...,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN
15,AD,2005,5.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
16,AD,2006,8.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
17,AD,2007,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN
18,AD,2008,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
19,AE,1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,AE,1981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,AE,1982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,AE,1983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,AE,1984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,AE,1985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,AE,1986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,AE,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,AE,1988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,AE,1989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,AE,1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5739,ZM,2008,13211.0,NaN,NaN,101.0,1120.0,3244.0,2094.0,737.0,...,NaN,NaN,165.0,1246.0,2062.0,1114.0,498.0,187.0,115.0,0.0
5740,ZW,1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5741,ZW,1981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5742,ZW,1982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5743,ZW,1983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5744,ZW,1984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5745,ZW,1985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5746,ZW,1986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5747,ZW,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5748,ZW,1988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5749,ZW,1989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5750,ZW,1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5751,ZW,1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5752,ZW,1992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5753,ZW,1993,5331.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5754,ZW,1994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5755,ZW,1995,8965.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5756,ZW,1996,11965.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5757,ZW,1997,14512.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5758,ZW,1998,14492.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5759,ZW,1999,14414.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5760,ZW,2000,14392.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5761,ZW,2001,15370.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5762,ZW,2002,15941.0,NaN,NaN,191.0,600.0,2548.0,1662.0,744.0,...,NaN,NaN,222.0,914.0,2185.0,1095.0,421.0,140.0,65.0,NaN
5763,ZW,2003,14488.0,NaN,NaN,133.0,874.0,3048.0,2228.0,981.0,...,NaN,NaN,180.0,1232.0,2856.0,1480.0,565.0,225.0,114.0,NaN
5764,ZW,2004,14581.0,NaN,NaN,187.0,833.0,2908.0,2298.0,1056.0,...,NaN,NaN,225.0,1140.0,2858.0,1565.0,622.0,214.0,111.0,NaN
5765,ZW,2005,13155.0,NaN,NaN,210.0,837.0,2264.0,1855.0,762.0,...,NaN,NaN,269.0,1136.0,2242.0,1255.0,578.0,193.0,603.0,NaN
5766,ZW,2006,12718.0,NaN,NaN,215.0,736.0,2391.0,1939.0,896.0,...,NaN,NaN,237.0,1020.0,2424.0,1355.0,632.0,230.0,96.0,NaN
5767,ZW,2007,10583.0,6.0,132.0,138.0,500.0,3693.0,0.0,716.0,...,7.0,178.0,185.0,739.0,3311.0,0.0,553.0,213.0,90.0,NaN
5768,ZW,2008,9830.0,NaN,NaN,127.0,614.0,0.0,3316.0,704.0,...,NaN,NaN,145.0,840.0,0.0,2890.0,467.0,174.0,105.0,0.0

In [9]:
s = tb.melt(id_vars=['iso2','year'])

In [11]:
s.dropna() # NaN 제거

       iso2  year   variable   value
4        AD  1993     new_sp    15.0
5        AD  1994     new_sp    24.0
6        AD  1996     new_sp     8.0
7        AD  1997     new_sp    17.0
8        AD  1998     new_sp     1.0
9        AD  1999     new_sp     4.0
10       AD  2000     new_sp     1.0
11       AD  2001     new_sp     3.0
12       AD  2002     new_sp     2.0
13       AD  2003     new_sp     7.0
14       AD  2004     new_sp     3.0
15       AD  2005     new_sp     5.0
16       AD  2006     new_sp     8.0
17       AD  2007     new_sp     2.0
18       AD  2008     new_sp     3.0
35       AE  1999     new_sp    31.0
36       AE  2000     new_sp    73.0
37       AE  2001     new_sp    69.0
38       AE  2002     new_sp    57.0
39       AE  2003     new_sp    77.0
40       AE  2004     new_sp    57.0
41       AE  2005     new_sp    62.0
42       AE  2006     new_sp    52.0
43       AE  2007     new_sp    56.0
44       AE  2008     new_sp    50.0
57       AF  1997     new_sp   618.0
58       AF  1998     new_sp  1833.0
59       AF  1999     new_sp  1669.0
60       AF  2000     new_sp  2892.0
61       AF  2001     new_sp  4639.0
...     ...   ...        ...     ...
120309   SZ  2008  new_sp_fu     0.0
120387   TG  2008  new_sp_fu     0.0
120442   TJ  2005  new_sp_fu     0.0
120444   TJ  2007  new_sp_fu     0.0
120445   TJ  2008  new_sp_fu     0.0
120471   TK  2008  new_sp_fu     0.0
120479   TL  2008  new_sp_fu     0.0
120504   TM  2005  new_sp_fu     0.0
120505   TM  2006  new_sp_fu     0.0
120506   TM  2007  new_sp_fu     0.0
120565   TO  2008  new_sp_fu     0.0
120589   TR  2005  new_sp_fu     0.0
120590   TR  2006  new_sp_fu     0.0
120591   TR  2007  new_sp_fu     0.0
120592   TR  2008  new_sp_fu     0.0
120621   TT  2008  new_sp_fu     0.0
120649   TV  2008  new_sp_fu     0.0
120705   UA  2006  new_sp_fu     0.0
120706   UA  2007  new_sp_fu     0.0
120734   UG  2008  new_sp_fu     0.0
120763   US  2008  new_sp_fu     0.0
120792   UY  2008  new_sp_fu     0.0
120819   UZ  2007  new_sp_fu     0.0
120878   VE  2008  new_sp_fu     0.0
120935   VN  2008  new_sp_fu     0.0
120964   VU  2008  new_sp_fu     0.0
121038   YE  2008  new_sp_fu     0.0
121092   ZA  2008  new_sp_fu     0.0
121119   ZM  2008  new_sp_fu     0.0
121148   ZW  2008  new_sp_fu     0.0

[38619 rows x 4 columns]

In [12]:
s.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121149 entries, 0 to 121148
Data columns (total 4 columns):
iso2        120666 non-null object
year        121149 non-null int64
variable    121149 non-null object
value       38831 non-null float64
dtypes: float64(1), int64(1), object(2)
memory usage: 3.7+ MB

In [13]:
s.describe()

                year          value
count  121149.000000   38831.000000
mean     1994.229329    1282.241482
std         8.422569   11550.117273
min      1980.000000       0.000000
25%      1987.000000       5.000000
50%      1994.000000      45.000000
75%      2002.000000     318.000000
max      2008.000000  615977.000000

In [14]:
# 위 상태에서 Group By 를 사용할 수 있다.

In [15]:
s.dropna().groupby('variable').mean()

                     year        value
variable
new_sp        2000.507336  9112.137268
new_sp_f014   2001.680626   106.720389
new_sp_f04    2006.847328     6.417303
new_sp_f1524  2001.716807   761.138655
new_sp_f2534  2001.712490   857.329841
new_sp_f3544  2001.712668   587.705117
new_sp_f4554  2001.726016   401.766234
new_sp_f514   2006.849010    39.185644
new_sp_f5564  2001.709664   277.324370
new_sp_f65    2001.721243   256.435768
new_sp_fu     2007.022140     2.549815
new_sp_m014   2001.653570    79.711449
new_sp_m04    2006.852041     8.806122
new_sp_m1524  2001.697869   926.066026
new_sp_m2534  2001.700919  1304.247285
new_sp_m3544  2001.708455  1208.728446
new_sp_m4554  2001.714167   987.455754
new_sp_m514   2006.850374    28.975062
new_sp_m5564  2001.706250   699.392083
new_sp_m65    2001.700084   612.390142
new_sp_mu     2007.025735     5.731618

In [ ]:
# tidy data -> 분석하기 좋은 데이터