In [13]:
import pandas as pd
import collections # namedtuple이 collections 패키지안에 존재

In [14]:
df = pd.read_excel("https://github.com/chris1610/pbpython/blob/master/data/sample-salesv3.xlsx?raw=True")

In [15]:
#df["date"] = pd.to_datetime(df['date']) # 데이터가 한 개 있으면 Timestamp, 두 개 이상이면 index

In [16]:
df

,account number,name,sku,quantity,unit price,ext price,date
0,740150,Barton LLC,B1-20000,39,86.69,3380.91,2014-01-01 07:21:51
1,714466,Trantow-Barrows,S2-77896,-1,63.16,-63.16,2014-01-01 10:00:47
2,218895,Kulas Inc,B1-69924,23,90.70,2086.10,2014-01-01 13:24:58
3,307599,"Kassulke, Ondricka and Metz",S1-65481,41,21.05,863.05,2014-01-01 15:05:22
4,412290,Jerde-Hilpert,S2-34077,6,83.21,499.26,2014-01-01 23:26:55
5,714466,Trantow-Barrows,S2-77896,17,87.63,1489.71,2014-01-02 10:07:15
6,218895,Kulas Inc,B1-65551,2,31.10,62.20,2014-01-02 10:57:23
7,729833,Koepp Ltd,S1-30248,8,33.25,266.00,2014-01-03 06:32:11
8,714466,Trantow-Barrows,S1-50961,22,84.09,1849.98,2014-01-03 11:29:02
9,737550,"Fritsch, Russel and Anderson",S2-82423,14,81.92,1146.88,2014-01-03 19:07:37
10,146832,Kiehn-Spinka,S2-82423,15,67.74,1016.10,2014-01-03 19:39:53
11,688981,Keeling LLC,S2-00301,7,20.26,141.82,2014-01-04 00:02:36
12,786968,"Frami, Hills and Schmidt",S2-23246,6,61.31,367.86,2014-01-04 06:51:53
13,307599,"Kassulke, Ondricka and Metz",S2-10342,17,12.44,211.48,2014-01-04 07:53:01
14,737550,"Fritsch, Russel and Anderson",B1-53102,23,71.56,1645.88,2014-01-04 08:57:48
15,239344,Stokes LLC,S1-06532,34,71.51,2431.34,2014-01-04 11:34:58
16,672390,Kuhn-Gusikowski,S1-30248,14,72.75,1018.50,2014-01-04 19:59:02
17,239344,Stokes LLC,B1-50809,14,16.23,227.22,2014-01-04 22:14:32
18,141962,Herman LLC,S1-82801,10,94.30,943.00,2014-01-05 15:12:16
19,412290,Jerde-Hilpert,S2-00301,33,31.18,1028.94,2014-01-05 22:39:21
20,424914,White-Trantow,S2-00301,45,96.95,4362.75,2014-01-06 08:20:27
21,527099,Sanford and Sons,S1-30248,24,50.29,1206.96,2014-01-06 14:14:00
22,786968,"Frami, Hills and Schmidt",B1-04202,2,52.41,104.82,2014-01-06 15:53:49
23,714466,Trantow-Barrows,S1-30248,-1,16.97,-16.97,2014-01-06 18:27:28
24,786968,"Frami, Hills and Schmidt",S2-83881,34,60.41,2053.94,2014-01-06 23:38:31
25,729833,Koepp Ltd,S2-78676,5,14.75,73.75,2014-01-07 00:29:41
26,737550,"Fritsch, Russel and Anderson",B1-53636,42,42.06,1766.52,2014-01-08 00:02:11
27,672390,Kuhn-Gusikowski,S2-83881,42,63.87,2682.54,2014-01-08 10:00:08
28,714466,Trantow-Barrows,B1-38851,4,60.04,240.16,2014-01-08 11:50:18
29,729833,Koepp Ltd,B1-86481,6,81.79,490.74,2014-01-08 17:46:40
...,...,...,...,...,...,...,...
1470,218895,Kulas Inc,S2-00301,-1,63.08,-63.08,2014-12-23 08:29:30
1471,218895,Kulas Inc,S2-00301,9,40.83,367.47,2014-12-23 08:44:32
1472,786968,"Frami, Hills and Schmidt",S1-30248,48,33.79,1621.92,2014-12-24 07:10:32
1473,740150,Barton LLC,B1-53102,3,54.07,162.21,2014-12-24 07:16:26
1474,729833,Koepp Ltd,B1-86481,43,26.47,1138.21,2014-12-24 09:50:26
1475,239344,Stokes LLC,B1-05914,46,82.07,3775.22,2014-12-24 18:04:20
1476,729833,Koepp Ltd,S1-50961,24,13.00,312.00,2014-12-24 19:33:58
1477,141962,Herman LLC,B1-05914,7,32.00,224.00,2014-12-24 22:54:28
1478,307599,"Kassulke, Ondricka and Metz",S1-50961,9,96.54,868.86,2014-12-25 00:04:04
1479,163416,Purdy-Kunde,S1-30248,42,43.69,1834.98,2014-12-25 01:22:00
1480,146832,Kiehn-Spinka,S1-82801,26,85.59,2225.34,2014-12-25 03:48:04
1481,163416,Purdy-Kunde,S2-77896,9,23.58,212.22,2014-12-25 06:14:53
1482,672390,Kuhn-Gusikowski,S2-83881,11,50.25,552.75,2014-12-26 06:53:40
1483,729833,Koepp Ltd,S1-47412,31,85.90,2662.90,2014-12-26 08:30:34
1484,688981,Keeling LLC,S2-82423,15,56.64,849.60,2014-12-26 13:18:51
1485,737550,"Fritsch, Russel and Anderson",B1-04202,6,58.78,352.68,2014-12-26 18:31:15
1486,424914,White-Trantow,S2-00301,-1,22.99,-22.99,2014-12-27 07:14:09
1487,257198,"Cronin, Oberbrunner and Spencer",S1-50961,5,89.19,445.95,2014-12-28 09:19:21
1488,786968,"Frami, Hills and Schmidt",S1-47412,39,49.46,1928.94,2014-12-28 10:11:13
1489,239344,Stokes LLC,S1-93683,47,25.48,1197.56,2014-12-28 13:21:03
1490,604255,"Halvorson, Crona and Champlin",B1-86481,40,23.23,929.20,2014-12-29 13:32:18
1491,257198,"Cronin, Oberbrunner and Spencer",S2-77896,19,33.18,630.42,2014-12-29 14:23:37
1492,714466,Trantow-Barrows,B1-53102,32,34.71,1110.72,2014-12-29 17:43:04
1493,146832,Kiehn-Spinka,S1-50961,27,95.90,2589.30,2014-12-30 02:25:21
1494,786968,"Frami, Hills and Schmidt",B1-86481,8,74.01,592.08,2014-12-30 12:38:25
1495,737550,"Fritsch, Russel and Anderson",S1-06532,12,55.80,669.60,2014-12-30 13:38:13
1496,786968,"Frami, Hills and Schmidt",S1-06532,37,13.14,486.18,2014-12-30 21:42:17
1497,239344,Stokes LLC,S2-10342,14,38.75,542.50,2014-12-30 22:45:19
1498,642753,Pollich LLC,S2-82423,3,65.97,197.91,2014-12-31 10:36:24
1499,383080,Will LLC,S2-00301,38,46.44,1764.72,2014-12-31 12:48:35

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 7 columns):
account number    1500 non-null int64
name              1500 non-null object
sku               1500 non-null object
quantity          1500 non-null int64
unit price        1500 non-null float64
ext price         1500 non-null float64
date              1500 non-null object
dtypes: float64(2), int64(2), object(3)
memory usage: 82.1+ KB

In [18]:
# account number -> category data , date 를 datetime을 변환 pd.to_, sku 값 이상?

In [19]:
df["account number"] = df["account number"].astype('category')

In [20]:
df["date"] = pd.to_datetime(df['date'])

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 7 columns):
account number    1500 non-null category
name              1500 non-null object
sku               1500 non-null object
quantity          1500 non-null int64
unit price        1500 non-null float64
ext price         1500 non-null float64
date              1500 non-null datetime64[ns]
dtypes: category(1), datetime64[ns](1), float64(2), int64(1), object(2)
memory usage: 72.6+ KB

In [22]:
df.set_index('date').groupby('name')["ext price"].resample("M").sum().head(20) # 시계열 분석의 set_index 방식

name                             date
Barton LLC                       2014-01-31     6177.57
                                 2014-02-28    12218.03
                                 2014-03-31     3513.53
                                 2014-04-30    11474.20
                                 2014-05-31    10220.17
                                 2014-06-30    10463.73
                                 2014-07-31     6750.48
                                 2014-08-31    17541.46
                                 2014-09-30    14053.61
                                 2014-10-31     9351.68
                                 2014-11-30     4901.14
                                 2014-12-31     2772.90
Cronin, Oberbrunner and Spencer  2014-01-31     1141.75
                                 2014-02-28    13976.26
                                 2014-03-31    11691.62
                                 2014-04-30     3685.44
                                 2014-05-31     6760.11
                                 2014-06-30     5379.67
                                 2014-07-31     6020.30
                                 2014-08-31     5399.58
Name: ext price, dtype: float64

In [23]:
# 시계열 분석
# 1. 그래프 -> plot
# 2. 구간별로 묶기 -> resample

In [24]:
# object끼리 묶는 게 groupby 이다. 
# category끼리 묶는 게 crosstab 이다.
# 구간별로 묶는 게 resample 이다.